### ISSUE TITLE
Error in bash scripts/llama-2-7b-chat.sh

### ISSUE THREAD

**Issue by txy77** [wang-research-lab/agentinstruct#1]
How can I deal with it?

Traceback (most recent call last):
  File "/home/tangxinyu/anaconda3/envs/po/lib/python3.10/site-packages/retrying.py", line 251, in call
    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
  File "/home/tangxinyu/agentinstruct/src/agentinstruct/reasoning/helm/src/helm/proxy/clients/auto_client.py", line 153, in make_request_with_retry
    return client.make_request(request, prompt_list)
  File "/home/tangxinyu/agentinstruct/src/agentinstruct/reasoning/helm/src/helm/common/hierarchical_logger.py", line 104, in wrapper
    return fn(*args, **kwargs)
  File "/home/tangxinyu/agentinstruct/src/agentinstruct/reasoning/helm/src/helm/proxy/clients/local_client.py", line 271, in make_request
    response, full_text, cot = do_it()
  File "/home/tangxinyu/agentinstruct/src/agentinstruct/reasoning/helm/src/helm/proxy/clients/local_client.py", line 87, in do_it
    response = requests.post(f"{LocalClient.INFERENCE_ENDPOINT}{request.model_engine}", json=raw_request_copy)
  File "/home/tangxinyu/anaconda3/envs/po/lib/python3.10/site-packages/requests/api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "/home/tangxinyu/anaconda3/envs/po/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/tangxinyu/anaconda3/envs/po/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/tangxinyu/anaconda3/envs/po/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/home/tangxinyu/anaconda3/envs/po/lib/python3.10/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='serve-container', port=8081): Max retries exceeded with url: /predictions/llama-2-7b-chat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f20908bc5e0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))

**Comment by kylemontgomery1** [comment]
For llama-2-7b-chat, you'll need to follow [this guide](https://github.com/wang-research-lab/agentinstruct/blob/main/src/agentinstruct/reasoning/serve/README.md) to deploy the model locally.

**Comment by pkulium** [comment]
great work! Is there another way to run the inference without using this pytorch serve?

**Comment by pkulium** [comment]
I got this error ''pytorch serve Invalid configuration: null'' even though the config file is correct
